name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.4
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/4.4.stable ~/.local/share/godot/export_templates/4.4.stable

      - name: Import assets
        run: godot --headless --verbose --editor --quit

      - name: Install Android build template
        run: |
          mkdir -p android/build
          unzip -q ~/.local/share/godot/export_templates/4.4.stable/android_source.zip -d android/build

      - name: Android Build
        run: |
          mkdir -v -p build/android
          godot --headless --verbose --export-debug "Android" build/android/rough-rider.apk
          test -f build/android/rough-rider.apk || (echo "APK was not created!" && exit 1)

      - name: Upload APK as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rough-rider-apk
          path: build/android/*.apk

      - name: Attach APK to a Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          files: build/android/*.apk
